### ISSUE TITLE
amd64 image

### ISSUE THREAD

**Issue by adelorenzo** [lomorage/homepage#1]
Hello,

Thank you for your project. Are there any plans of developing a intel/amd docker image of lomorage? I have an old machine I use as a home server and lomorage would be perfect to backup my photos.

I would be happy to help develop the intel/amd64 docker image with your guidance.

Regards,
Adolfo Delorenzo

**Comment by aisnote** [comment]
There is one blog on setup lomorage with docker on Windows10:
https://lomorage.com/blog/2020/11/16/windows-docker/

**Comment by fuji246** [comment]
fixed in https://github.com/lomorage/lomo-docker/commit/5ae68e752e58f27f5f083212035ebda1c020eee9
