### ISSUE TITLE
能否支持MIPS架构处理器

### ISSUE THREAD

**Issue by larusx** [lomorage/homepage#12]
型号是R3D，可以安装entware，应该支持起来还可以。

**Comment by fuji246** [comment]
谢谢，很好的建议，xiaomi R3D配置不错，entware源比openwrt默认的源软件多多了。在wd N750上试了下相关的依赖ffmpeg和exiftool都支持，libvips还没有。我们接下来会看一下。

**Comment by larusx** [comment]
我说错了，是R3P，不内置硬盘需要自己外接的那种

**Comment by fuji246** [comment]
可以试试了，https://github.com/lomorage/openwrt-packages#quick-start
