### ISSUE TITLE
web端使用nginx反代HTTPS后，提示登陆失败

### ISSUE THREAD

**Issue by Kissycat** [lomorage/homepage#13]
求助
内容如题
用的是官方的docker镜像，在不使用ssl代理的端口表现一切正常，但是ssl代理后就会出现无法登陆的情况。通过域名访问的结果也是相同。
![avatar](https://dlg.lovegood.cyou/s/4jv7r5)
域名证书是复用的，*.domain.com这种

然后这是nginx反代的内容：

server {                                         
    listen       987 ssl;                        
    server_name  localhost;                      
                                                                                                  
    ssl_certificate      /etc/nginx/ssl/cert.pem;
    ssl_certificate_key  /etc/nginx/ssl/key.pem; 
    ssl_session_timeout  5m;                     
                                                 
    location / {                                 
        proxy_pass http://localhost:9987;          
    }                                            
}

我一只小菜鸡折腾了半天实在不知道哪里出问题了，网上也搜不到类似情况。

登陆失败好像还不写入lomorage的日志，容器外的nginx日志也没有报错。

然后也没找到lomorege容器内添加ssl的方法。。。😭
![avatar](https://dlg.lovegood.cyou/s/li1cxx)

对了，使用安卓客户端登录使用相同方式反代https的服务器端，又是正常可用的，只有web端有这问题。

求开发大佬帮忙分析一波 @fuji246

**Comment by fuji246** [comment]
Lomo-web是个web client，也是通过rest api来和lomod交互的，启动的时候会配置lomod的host和port，而且现在是http访问的，https://github.com/lomorage/lomo-docker/blob/master/entry.sh#L17。看上面的截图应该是用的172.17.0.8:8000，你可以在浏览器调试窗口打开看看是不是用的这个ip port，可以改一下HOST参数试试，https://github.com/lomorage/lomo-docker/blob/master/run.sh#L28。

后面我们会把lomo-web合并到lomod，应该能省去一些配置的麻烦。

**Comment by fuji246** [comment]
@CDLLY, lomo-web is integrated with lomod now, now they by default both served at port 8000, so you don't need to configure the host and port anymore, you can upgrade to give it a try.
