### ISSUE TITLE
repo not secure

### ISSUE THREAD

**Issue by glenerrington** [lomorage/homepage#17]
followed the instuctions https://lomorage.com/installation-pi/ when  ran sudo apt update i get the following output

`pi@raspberrypi:~ $ sudo apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease                
Ign:3 https://lomoware.github.io/debian/buster buster InRelease             
Err:4 https://lomoware.github.io/debian/buster buster Release
  Redirection from https to 'http://lomoware.lomorage.com/debian/buster/dists/buster/Release' is forbidden [IP: 185.199.111.153 443]
Reading package lists... Done
E: The repository 'https://lomoware.github.io/debian/buster buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

os version output
` cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

**Comment by fuji246** [comment]
sorry for the confusion,  I think the above doc is outdated one and not removed, the latest one is at https://docs.lomorage.com/docs/Installation/lomorage-service/installation-raspbian/

**Comment by glenerrington** [comment]
can  I make a sugestion update the instructions and not delete them.

Thans for getting back to me this quickly.
