### ISSUE TITLE
sudo apt-key add

### ISSUE THREAD

**Issue by glenerrington** [lomorage/homepage#18]
you need to update the method of importing the gpg key apt-key was deprecated in debian 11 aI am running bullseye as you now support this

wget -qO - https://lomoware.lomorage.com/debian/gpg.key | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

**Comment by glenerrington** [comment]
I want to help push this project of yours but with the use of apt-key is stopping me and after bullseye I think raspberry pi OS will not be supporting it any more

**Comment by dwebfan** [comment]
thank for the reminder! We'll fix it.

**Comment by fuji246** [comment]
@glenerrington , you can use `curl -fsSL https://lomoware.lomorage.com/debian/gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/lomorage-apt-key.gpg > /dev/null` instead.

I've already updated the doc as well.
