### ISSUE TITLE
openwrt的mipsel源没有了

### ISSUE THREAD

**Issue by xiangfeigao** [lomorage/homepage#19]
src/gz lomorage https://lomostaging.lomorage.com/opkg/mips-3.4
openwrt的mipsel源没有了，还是有新地址，自己编译出错了几次，放弃了，希望提供

**Comment by fuji246** [comment]
should be lomoware.lomorage.com/opkg/mipsel-3.4

**Comment by fuji246** [comment]
should be there, https://github.com/lomoware/lomoware.github.io/tree/master/opkg.
Please switch to `src/gz lomorage https://lomoware.lomorage.com/opkg/[architecture]`
