### ISSUE TITLE
docker version of lomorange , the port of web server and the port of app server is reversed.

### ISSUE THREAD

**Issue by wingser** [lomorage/homepage#2]
docker version of lomorange , the port of web server and the port of app server is reversed.
the default web server is 192.168.x.x:8001

**Comment by fuji246** [comment]
@wingser , you can change the port of lomow and lomod, see the doc here: https://github.com/lomorage/lomo-docker#run

**Comment by wingser** [comment]
I know how to config it, but its a bug in default show

**Comment by dwebfan** [comment]
@wingser can you please briefly describe the bug? I'm unable to locate the bug.
