### ISSUE TITLE
Exclamation mark on ios app

### ISSUE THREAD

**Issue by darrepac** [lomorage/homepage#22]
Hello

What those exclamations marks mean? (knowing that all my photo have been imported)

![20220711_070800000_iOS](https://user-images.githubusercontent.com/7128994/178208945-2749fc60-4826-41be-991c-ef798b2e776a.png)

I have the logs available but don't know if it is so secure to share it here

**Comment by fuji246** [comment]
Looks like some problem on fetching the preview, you can share the log via email to support@lomorage.com

**Comment by darrepac** [comment]
```
 Looks like there is a lot of file missing in the file system but exists in db, so inconsistent between the two.

check lomod.log and some logs below:

time="2022-07-11T03:28:31Z" level=warning msg="User 's /media/primary/pascal/Photos/master/2007/06/17/20070617_42909.jpg is not found in file system, remove from DB"
time="2022-07-11T03:28:32Z" level=warning msg="User 's /media/primary/pascal/Photos/master/2007/06/17/20070617_26993.jpg is not found in file system, remove from DB"
time="2022-07-11T03:28:32Z" level=warning msg="User 's /media/primary/pascal/Photos/master/2007/06/17/20070617_26951.jpg is not found in file system, remove from DB"
time="2022-07-11T03:28:32Z" level=warning msg="User 's /media/primary/pascal/Photos/master/2007/06/17/20070617_26960.jpg is not found in file system, remove from DB"
time="2022-07-11T03:28:32Z" level=warning msg="User 's /media/primary/pascal/Photos/master/2007/06/17/20070617_26985.jpg is not found in file system, remove from DB"
time="2022-07-11T03:28:33Z" level=warning msg="User 's /media/primary/pascal/Photos/master/2007/06/17/20070617_26968.jpg is not found in file system, remove from DB"
time="2022-07-11T03:28:33Z" level=warning msg="User 's /media/primary/pascal/Photos/master/2007/06/17/20070617_26968.jpg is not found in file system, remove from DB"

Maybe you tried to remove the assets, restart over but not delete the database file? Those records should be deleted from database automatically, and everything should back to normal, you can try restart lomod and restart iOS APP (or may need reinstall iOS APP), let me know if that works.
```

Well I did not touch any photos. May-be it come from the fact that I did a massive import with `-n` option ?? so it is normal to not find the file at this place??

**Comment by fuji246** [comment]
@dwebfan could you confirm?

**Comment by fuji246** [comment]
@darrepac , once those records are cleaned, are you still having the problem?

**Comment by darrepac** [comment]
Well, I have no more such exclamation mark cause I have no more photos... Only remains the ones that was from my camera roll.
It has deleted from db all the 40k that I have imported previously (with `--no-move`) during days :(

**Comment by fuji246** [comment]
find the problem on backend, will fix it this week.

**Comment by darrepac** [comment]
ok keep me updated

**Comment by fuji246** [comment]
@darrepac , could you update lomod and try import again with `--no-move`?

**Comment by darrepac** [comment]
On going (will take several days with all photos and videos...)

**Comment by darrepac** [comment]
So I started the import again. But as I did it previously, all the thumbnails and video previews are already present, but lomoc import is recreating it, it seems. There is no option or check if the preview file is already present?

**Comment by fuji246** [comment]
Did you start from scratch? Did you remove those imported before? Assuming
you just reimport while keeping previously imported there, it should be
able to deduplicate already imported ones, and only import those that are
missing. If assets are removed, the thumbnails are supposed to be removed
as well, that said, there is currently no option to check if preview files
are already present, those should be removed when assets are removed, if
it's there, there should be a bug somewhere. Maybe @Dweb Fan
***@***.***> can comment.

**Comment by darrepac** [comment]
I have the feeling that I have a mix of both:
If I do `find . -name *.* | wc -l` in preview folder, it gives 5500
On one side, 5500 is much less than my 40k assets that I imported, lost, and I am currently importing again
On the other, it is much more that my basis assets before importation... and I do not see those 5500 files in lomorage user interface...but in container logs I see `time="2022-07-21T21:24:20Z" level=info msg="IN PROGRESS: scanned 32 directories, and imported 4965 media files"` so not too far from 5500.
Well let see at the end of the import....

**Comment by darrepac** [comment]
Importing still running… 
I am a bit afraid because the mobile app is not showing any added assets… but maybe it is due to my server running at 100% CPU and not answering on time requests (?)

**Comment by fuji246** [comment]
@darrepac , how is the import going?

**Comment by darrepac** [comment]
Still running after 12 days… that’s why I asked a progress status somewhere ;)
In any case, I am back home for 1 day and leaving for 2 weeks.
But next time, I will follow your recommendation and import only one folder…

**Comment by darrepac** [comment]
> Still running after 12 days… that’s why I asked a progress status somewhere ;)

Have seen this in the log: level=info msg="IN PROGRESS: scanned 635 directories, and imported 1370 media files"
Is this a progress status?
Can't you:
- update the status after each asset imported
- at least say the total number of directories it will scan in order to know where we are (unless you don't know at this stage?)

**Comment by fuji246** [comment]
Currently lomoc import is via API call to the backend, we should be able to add some logs in lomod.log to show where we are , currently seems it only print warn/err logs.

**Comment by fuji246** [comment]
I'm surprised the import is still ongoing, sorry about that. Are you using more powerful PC now?

**Comment by darrepac** [comment]
> I'm surprised the import is still ongoing, sorry about that. Are you using more powerful PC now?

Well no... didn't have the time to setup when I was home.
I made a new import to get the new photos I made in the meantime... so now, I don't know if the first import is still going or I have only the second one. But on the best scenario, it would mean it took 1 month to import my database...

Nevertheless, yes it is slow and yes the server CPU, hdd has a direct impact. Yet by trying different solution with same server (Librephoto, Photoprism, Photoview, Home Gallery etc), I can say that Lomorage is on the slow side... may-be something to improve. At a first guess, video is one clear bottleneck particularly as lomorage is transcoding on different resolution for 1 video.

**Comment by darrepac** [comment]
No way to see the progress status?

**Comment by dwebfan** [comment]
> No way to see the progress status?

Will add in next release.

**Comment by fuji246** [comment]
@darrepac , could you update and try again?

**Comment by fuji246** [comment]
close it now, feel free to reopen if it still happens.

**Comment by darrepac** [comment]
> @darrepac , could you update and try again?

I am really busy this end of the year. Hope to be able to help you later on
