### ISSUE TITLE
openwrt源已失效，请求修复

### ISSUE THREAD

**Issue by ropon** [lomorage/homepage#25]
openwrt源失效了 https://lomostaging.lomorage.com/opkg/mips-3.4/

**Comment by fuji246** [comment]
这个应该是好的，直接访问上面的链接是不行的，但设置成源应该是没问题的。

比如下载https://lomostaging.lomorage.com/opkg/mips-3.4/lomo-backend_35fa4103-29_mips-3.4.ipk。

另外现在已经都更新到用https://lomoware.lomorage.com/opkg了， 参考这里的安装说明 https://github.com/lomorage/openwrt-packages

**Comment by ropon** [comment]
好的，谢谢

**Comment by ropon** [comment]
root@OpenWrt:~# opkg install lomo-backend --no-check-certificate
Package libwebp version 1.2.0-3 has no valid architecture, ignoring.
Package lomo-backend version 35fa4103-29 has no valid architecture, ignoring.
Package libwebp version 1.2.0-3 has no valid architecture, ignoring.
Package lomo-backend version 35fa4103-29 has no valid architecture, ignoring.
Package libwebp version 1.2.0-3 has no valid architecture, ignoring.
Package lomo-backend version 35fa4103-29 has no valid architecture, ignoring.
Package libwebp version 1.2.0-3 has no valid architecture, ignoring.
Package lomo-backend version 35fa4103-29 has no valid architecture, ignoring.
Unknown package 'lomo-backend'.
Collected errors:
 * opkg_install_cmd: Cannot install package lomo-backend.

**Comment by ropon** [comment]
root@OpenWrt:~# opkg install lomo-backend_35fa4103-29_mips-3.4.ipk
Package libwebp version 1.2.0-3 has no valid architecture, ignoring.
Package vips version 8.11.4-2 has no valid architecture, ignoring.
Package libwebp version 1.2.0-3 has no valid architecture, ignoring.
Package vips version 8.11.4-2 has no valid architecture, ignoring.
Package libwebp version 1.2.0-3 has no valid architecture, ignoring.
Package vips version 8.11.4-2 has no valid architecture, ignoring.
Package libwebp version 1.2.0-3 has no valid architecture, ignoring.
Package vips version 8.11.4-2 has no valid architecture, ignoring.
Unknown package 'lomo-backend'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for lomo-backend found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package lomo-backend.

**Comment by ropon** [comment]
另外请问下
IOS 应用程序
睡眠模式下后台自动上传是？
IOS锁屏下不会自动上传同步照片呢

**Comment by fuji246** [comment]
iOS只有自家iCloud让这么干，第三方应用不行。

**Comment by ropon** [comment]
重启后提示
time="2022-07-15T00:52:06Z" level=error msg="http reply: Device is not mounted yet"
实际是挂载的
另外时不时还报：
time="2022-07-14T14:25:00Z" level=warning msg="read overlayfs:/overlay uuid via lsblk: lsblk -o UUID -P overlayfs:/overlay:  lsblk: overlayfs:/overlay: not a block device\n: exit status 32"

time="2022-07-14T14:25:00Z" level=warning msg="read overlayfs:/overlay uuid via blkid: blkid -o export -p --uuid -i overlayfs:/overlay:  : exec: \"blkid\": executable file not found in $PATH"

实际lsblk blkid命令是存在的
root@OpenWrt:~# which blkid
/opt/sbin/blkid
root@OpenWrt:~# which lsblk
/opt/bin/lsblk

**Comment by ropon** [comment]
这是生成缩略图失败了么？
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/47031463/179457867-aed79ca6-9250-4340-a7f2-cfde7e5f20ff.png">

**Comment by ropon** [comment]
大量此类错误

**Comment by ropon** [comment]
折腾几天还是放弃了，硬件不行没法
https://www.ropon.top/824.html

**Comment by ropon** [comment]
折腾几天还是放弃了，硬件不行没法
https://www.ropon.top/824.html

**Comment by ropon** [comment]
看了下openwrt安装ffmpeg默认不支持webp么，可设置生成缩略图为其他格式么？
root@OpenWrt:~# ffmpeg -encoders|grep webp
ffmpeg version 4.3.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8.4.0 (OpenWrt GCC 8.4.0 r16616-6f89233c41)
  configuration: --enable-cross-compile --cross-prefix=mipsel-openwrt-linux-musl- --arch=mipsel --cpu=24kc --target-os=linux --prefix=/usr --pkg-config=pkg-config --enable-shared --enable-static --enable-pthreads --enable-zlib --disable-doc --disable-debug --disable-lzma --disable-vaapi --disable-vdpau --disable-outdevs --disable-altivec --disable-vsx --disable-power8 --disable-armv5te --disable-armv6 --disable-armv6t2 --disable-fast-unaligned --disable-runtime-cpudetect --disable-x86asm --enable-gnutls --disable-decoder=atrac3 --disable-decoder=h264 --disable-decoder=hevc --disable-decoder=vc1 --disable-muxer=h264 --disable-muxer=hevc --disable-muxer=vc1 --disable-demuxer=h264 --disable-demuxer=hevc --disable-demuxer=vc1 --disable-parser=h264 --disable-parser=hevc --disable-parser=vc1 --enable-libopus --enable-small --enable-libshine --enable-libfdk-aac
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100

**Comment by ropon** [comment]
Automatic encoder selection failed for output stream #0:0. Default encoder for format webp (codec webp) is probably disabled. Please choose an encoder manually.
Error selecting an encoder for stream 0:0

**Comment by fuji246** [comment]
谢谢， ffmepg这个要重新编译一下，加到https://github.com/lomorage/openwrt-packages，这个我最近看看。

**Comment by fuji246** [comment]
ffmpeg need recompile to support h265 hevc and webp, probably not the correct way to do this on low end devices, need to think about other solutions like use iOS/Android to generate the preview and upload then...
