### ISSUE TITLE
Offload import process

### ISSUE THREAD

**Issue by darrepac** [lomorage/homepage#26]
Hi,

Is there a mean to offload the import process?
I have a big set of pictures and video that take age to import (due to transcoding and my server processor not being the latest one)
For doing so I am doing an import with no move option in the container running on my server.
Is there a mean to run this import from a more powerful machine yet filling the database in the container server? (I have a windows desktop PC which is more powerful)

**Comment by fuji246** [comment]
You can import that with more powerful machine and then change the home directory once you move it to power efficient server. see https://docs.lomorage.com/docs/Usage/lomorage-client/#reset-users-backup-home-directory-and-backup-directory

**Comment by darrepac** [comment]
Ok but I thought using another machine but with the same home directory (home directory is on a NAS).
There will be no conflict having 2 lomo instance on 2 different machines pointing on to the same home directory?

**Comment by fuji246** [comment]
should be fine, but I guess remote mount the NAS as Homer directory is more
likely to be the bottleneck than CPU?

**Comment by darrepac** [comment]
That’s why I am currently running lomorage on my NAS… but seeing that after 15days, import is still not finished, I guess CPU is more the bottleneck (and videos)

I don’t know if the windows executable as an import with « no move » option. If yes, I think the problem will be how yo replace the absolute path of assets in the database

**Comment by fuji246** [comment]
One option is to use Linux machine or VM to import, and mount it with the same path you are going to use later.

**Comment by darrepac** [comment]
👍

**Comment by fuji246** [comment]
@darrepac , to speed up import process, now "--no-video" is added to skip video import, see https://docs.lomorage.com/docs/Usage/lomorage-client/#import-from-one-existing-folders

**Comment by fuji246** [comment]
close it now, feel free to reopen if it still happens.
