### ISSUE TITLE
Settings issue

### ISSUE THREAD

**Issue by darrepac** [lomorage/homepage#27]
Hi

I have disabled photos upload from my iPhone to avoid to surcharge my server while it is still importing (it starts to be verrrrry long), so I put following settings:
![B03028D0-6DC2-48B3-BF95-A2E4976CD18B](https://user-images.githubusercontent.com/7128994/184278394-b3428bc2-e241-4cfa-8383-21d3cf10e670.png)

but then I got following error « cellular download disable » while it is not:
![21EDECA2-F752-40D3-8E68-5C428880CAB1](https://user-images.githubusercontent.com/7128994/184278485-cbca5e5c-6c76-4e24-92bf-8e9234eef8e4.jpeg)

something weird isn’t it? 
i sent you my logs by email

thx

**Comment by fuji246** [comment]
looks like some connectivity issues, there are two ip addresses tried, neither reachable, could you try Lomorage web client access?

**Comment by darrepac** [comment]
Ok so cpu problem probably (and short timeout?). The error message was confusing

Thx

**Comment by darrepac** [comment]
I know that my network is not very fast and the cpu is highly used by ffmpeg conversion for import, but with the same environment Plex succesfully deliver me my photos… so may-be the timeout in lomorage is too short??

**Comment by fuji246** [comment]
probably, could you try Lomorage Web App to see if it works?

**Comment by fuji246** [comment]
@darrepac , the latest lomod provide an option to disable video preview generation when import/upload, and it will generate on the fly if needed next time. See https://github.com/lomorage/lomod#preview-size-video.

**Comment by fuji246** [comment]
close it now, feel free to reopen if it still happens.
