### ISSUE TITLE
Rescan

### ISSUE THREAD

**Issue by darrepac** [lomorage/homepage#28]
Hello

What is the work done when you import again the same assets?
I did it for lomorage to check for new photos in the same directory...yet it seems to spend a lot of time on already imported photos doing exiftool to /tmp/ folder on it. Doesn't it check if the photo is already in the db before to do anything on it?

**Comment by dwebfan** [comment]
Good observation, thanks! I should check file exist or not before running exiftool. Will provide a fix very soon.

**Comment by fuji246** [comment]
@darrepac , you can update lomoc/lomod and try again.

**Comment by darrepac** [comment]
Sure? it seems that there is nothing new in docker.com:
[image: image.png]

Le dim. 28 août 2022 à 10:18, Jiantao Fu ***@***.***> a
écrit :

**Comment by fuji246** [comment]
just updated the docker image, should be available now.

**Comment by fuji246** [comment]
@darrepac , this should be fixed in latest release.

**Comment by fuji246** [comment]
close it now, feel free to reopen if it still happens.
