### ISSUE TITLE
Suggestions。

### ISSUE THREAD

**Issue by wingser** [lomorage/homepage#3]
1. Due to the docker version server can not auto discovered , can lomorage home page provide a QR code for discover and login？
2. Android app can not choose which folders should be backup , so many unnecessary pics will be backup .
3. mini  picture is a very good idea for web presentation， it will be much better shows them by month.

**Comment by fuji246** [comment]
All good suggestions, thank you

1. as for the QR code, wondering what is the best way to displace the QRcode, user may use terminal, and probably need to run a command to show the QRCode, but may save time for tedious input on the Phone. Or you have better idea?

2. We've heard same complains and we will prioritize that.

3. as for mini picture, are you talking about the grid view to show all the assets? We are thinking about provide more views like show by date.

**Comment by fuji246** [comment]
@wingser , mdns should work with this commit, https://github.com/lomorage/lomo-docker/commit/402d185636ac9c09d5ca47f68b0f9cb6e873932f
