### ISSUE TITLE
Photo transfer issue from iphone to unraid server running lomorage 

### ISSUE THREAD

**Issue by southernclipper** [lomorage/homepage#31]
Unraid 6.10.3 with IOS 16. Lomorage app uploaded about 8K of photos pretty quicking but now everytime I bring the app up on the IOS to finish the last 2K photos and it runs, I have been having a hard time getting the rest of the photos to sync to Unraid server. It starts to sync then slowing transfers a few photos over a 20min period and than appears to hang or is busy doing some else. Not sure if there are any settings I can change to make this work as designed.  I just updated the docker this morning for Lomorage on Unraid this morning hoping this would get it to start working. Any tips on what maybe the issue

**Comment by fuji246** [comment]
Could you send feedback email to support@lomorage.com with logs in iOS APP? It's in the settings tab, and will attach client and server logs automatically and send to support@lomorage.com and related developers.

**Comment by southernclipper** [comment]
> Could you send feedback email to [support@lomorage.com](mailto:support@lomorage.com) with logs in iOS APP? It's in the settings tab, and will attach client and server logs automatically and send to [support@lomorage.com](mailto:support@lomorage.com) and related developers.
Logs are on there way, let me know if you need anything else

**Comment by fuji246** [comment]
@southernclipper you can update and try again.

**Comment by fuji246** [comment]
@southernclipper , does that fixed the problem in your env?

**Comment by southernclipper** [comment]
I havent seen an update in the IOS app or Unraid docker app. The app still hangs after a few photos transfered and still hasnt tranfered all my photo to Lomorage since I reported it. Pleaes advise if you need additional info

**Comment by southernclipper** [comment]
I went to unraid console and issue a command to check for the latest lomorage service .
![image](https://user-images.githubusercontent.com/77412908/198326550-a3e6902b-28ac-48ba-826a-aaf21ef124ed.png)

**Comment by southernclipper** [comment]
I issue an update command in unraid console and says I am at the latest version, so still not fixed.

**Comment by fuji246** [comment]
@southernclipper, sorry, just pushed the new docker image now, https://hub.docker.com/repository/docker/lomorage/amd64-lomorage , the latest server version is aa72b47,

**Comment by southernclipper** [comment]
> @southernclipper, sorry, just pushed the new docker image now, https://hub.docker.com/repository/docker/lomorage/amd64-lomorage , the latest server version is aa72b47,

thanks all assets transfered as expected and seems to be working. thanks for the support

**Comment by fuji246** [comment]
close it now, feel free to reopen if it still happens.
