### ISSUE TITLE
IOS External Access Failure

### ISSUE THREAD

**Issue by OhNo2** [lomorage/homepage#32]
I am attempting to get my lomo service to connect to my iphone externally. I followed the nginx tutorial on the docs website to the letter, and I keep getting the error:

Can't retrieve status "[my.url:443]]"

I have been trying to see if it is a nginx error, but using it to connect from my computer is completely fine. so I have no idea what the problem is. 

Any help would be appreciated!

**Comment by fuji246** [comment]
Confirmed it's nginx conf problem, @OhNo2 , will close it for now.
