### ISSUE TITLE
备份的照片消失，不显示

### ISSUE THREAD

**Issue by Kissycat** [lomorage/homepage#33]
原先备份了几百张照片，一直正常用来着，不知道哪次更新之后（docker自动更新的），从lomorage的所有客户端都只能访问到其中固定的几张，照片数量也显示只有这么几张，重启无效。
![image](https://user-images.githubusercontent.com/20614068/215929218-680f330c-8419-45ac-b53c-37abce835f58.png)

不管是宿主机还是容器的文件系统都是可以正常访问到照片文件的，日志文件里除了无法获取到硬盘的uuid之外也没有其他报错，不过在扫描xx用户的储存目录时，速度非常快，好像真的只有这么几张照片一样...
![image](https://user-images.githubusercontent.com/20614068/215930558-aa2ff806-fd8d-4d92-97fd-3e2cbf483ddf.png)

容器也是特权容器。
![image](https://user-images.githubusercontent.com/20614068/215930070-58170f8a-00c2-45c8-b4c8-c261fe2c0a7e.png)

**Comment by fuji246** [comment]
照片都在是吗？可以看看数据库里面的记录是不是少了，有可能是掉盘后，db清理掉了，如果是这样，可以用命令行重现导入一下。

**Comment by Kissycat** [comment]
> 照片都在是吗？可以看看数据库里面的记录是不是少了，有可能是掉盘后，db清理掉了，如果是这样，可以用命令行重现导入一下。
是的，照片都还在。
可能确实有几次不正常关机，那请问应该怎样用命令行导入呢，删掉用户目录下的的db文件好像没有用..

**Comment by fuji246** [comment]
可以先试着把用户目录下的db文件拷贝过去，如果不行，再导入吧，参考
https://docs.lomorage.com/docs/Usage/lomorage-client/#import-from-one-existing-folders

**Comment by Kissycat** [comment]
感谢回复，问题解决了，原来还有个lomoc客户端程序可以用😂

Jiantao Fu ***@***.***> 于2023年2月11日周六 02:01写道：

> 可以先试着把用户目录下的db文件拷贝过去，如果不行，再导入吧，参考
>
> https://docs.lomorage.com/docs/Usage/lomorage-client/#import-from-one-existing-folders
>
