### ISSUE TITLE
can't create account

### ISSUE THREAD

**Issue by mxm145** [lomorage/homepage#6]
I install lomod in pi,everthing is fine.but, when I use my photon to create account,it says create account failed
In the server folder /media/pi, I see the folder used as my username
please tell me the reason

**Comment by dwebfan** [comment]
The SD card installing OS has only limited spaces and backup photos / video can easily fill up, so please plugin one USB drive, or setup remote network mount, then select your user directory under that directory, it would work.

**Comment by mxm145** [comment]
ok,it works now.thank you
