### ISSUE TITLE
Unable to start service

### ISSUE THREAD

**Issue by DVLZY** [lomorage/homepage#7]
Unable to start service
![image](https://user-images.githubusercontent.com/26837756/121774926-49a5fa00-cbb7-11eb-9e51-c26d78a2a5b1.png)

**Comment by aisnote** [comment]
1. 看看有没有 windows 默认的防火墙 把 lomod.exe 的进程给block 了。
2. 参考： https://docs.lomorage.com/zh/docs/Installation/lomorage-service/installation-win/，  第4条
服务起不来基本上都是因为  有 防火墙或者 杀毒软件把 lomod.exe 禁止了。

3.可以把 c:\Users\%username%\AppData\Local\lomoware\Lomoagent\lomoagent.log  这个log文件发上来看看。

谢谢

**Comment by taptictop** [comment]
装在c盘根目录可以,默认安装那一大串的就不行

均已放行了lomod.exe

**Comment by aisnote** [comment]
你电脑的用户名是什么？

-elliot

**Comment by taptictop** [comment]
5个普通字母,就像 abcde 这样

**Comment by aisnote** [comment]
@dwebfan  一起看看
@taptictop   能否把这个目录打包发上来？
c:\Users\%username%\AppData\Local\lomoware\var\log\

还有这个 log文件：  c:\Users\%username%\AppData\Local\lomoware\Lomoagent\lomoagent.log

**Comment by taptictop** [comment]
[var.rar.txt](https://github.com/lomorage/homepage/files/6813143/var.rar.txt)

去掉txt扩展名

是个新开的纯净报错log
有 默认启动报错
还有 32020启动报错-默认启动成功-停止-32020启动成功

**Comment by taptictop** [comment]
另外有办法不让imgXXXX.mov视频自动打包zip么...不太明白这样的意义,想用第三方软件来管理也不方便

**Comment by aisnote** [comment]
zip 应该是 动图（Apple的live photo）。普通的mov 不会打包成zip的

**Comment by taptictop** [comment]
> zip 应该是 动图（Apple的live photo）。普通的mov 不会打包成zip的

好的

**Comment by taptictop** [comment]
官网没发现pc端新版本,ios一切到设置就提示new version server found, please update

**Comment by aisnote** [comment]
贴个设置的 截图上来

**Comment by aisnote** [comment]
版本的问题，我们在查。
"Start serving at ::32030 (Version: 2021_05_22.21_58_37.0.a3acdbc)"
这个是你windows 的版本，应该是新的

**Comment by taptictop** [comment]
设置都没动,就扫码建了个新用户admin而已

**Comment by taptictop** [comment]
pc端保持不变,关掉了app再打开,提示还剩有xx个文件下拉同步,但是完全无法开始同步

只能删掉pc端配置重建用户,重头开始?

**Comment by aisnote** [comment]
重启一下 手机 app，试试

**Comment by taptictop** [comment]
没用...剩余数字可能是对的,就是续不了了

**Comment by aisnote** [comment]
在设置页面，发一个日志（反馈）给我们，谢谢

**Comment by taptictop** [comment]
从来都不配置系统邮箱的,发不了,算了哈..

**Comment by fuji246** [comment]
是不是网上下载的网图？

**Comment by taptictop** [comment]
不清楚,如果是一次性从头到尾可以

里面都是几年的几千个截图,下载图,视频,分不清

**Comment by fuji246** [comment]
搜索里面可以选择“未同步“，等上传完了再说吧。

**Comment by fuji246** [comment]
@DVLZY，问题有解决吗？

**Comment by DVLZY** [comment]
@fuji246 问题解决了，在我出差几天回到家后自己莫名其妙就修复了
